apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-peng-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
      - name: flaskapi
        image: peng:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9696